list:
	php artisan route:list

serve:
	php artisan serve

migrate:
	php artisan migrate

migrate-fresh:
	php artisan migrate:fresh

migrate-rollback:
	php artisan migrate:rollback

migrate-refresh:
	php artisan migrate:refresh

migrate-reset:
	php artisan migrate:reset

model:
	php artisan make:model -a --api

controller:
	php artisan make:controller --api

seeder:
	php artisan make:seeder

middleware:
	php artisan make:middleware
	
create-migrate:
	php artisan make:migration 

storage:
	php artisan storage:link

seed:
	php artisan db:seed

key-generate:
	php artisan key:generate

cors:
	php artisan config:publish cors

seed-permission:
	php artisan db:seed --class=PermissionSeeder

seed-role-permission:
	php artisan db:seed --class=RolePermissionSeeder
